### ISSUE TITLE
Prima Pagina

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/firstpage#2]
visualizza la pagina con un browser.
che differenza noti tra quello che
è stato scritto e quello che
viene visualizzato dal browser?

**Comment by luca998** [comment]
Che sul browser è tutto su un rigo non calcola gli spazi

**Comment by FabioZTessitore** [comment]
bene. Quindi d'ora in avanti quando scrivi una pagina web ricordati che gli spazi servono solo a te per rendere più chiaro il codice
