### ISSUE TITLE
I tag

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/firstpage#3]
Ho caricato tag.html.
Dammi l'ok quando tutto chiaro

**Comment by luca998** [comment]
Ok

**Comment by FabioZTessitore** [comment]
## Nidificare i tag

I tag possono essere inclusi all'interno di altri tag
prestando attenzione a chiudere prima il tag interno e poi quello esterno.

Es. Il tag `em` serve a mettere in evidenza una porzione del testo
e puo' naturalmente essere utilizzato all'interno di un paragrafo.

``` html
<p>Il linguaggio HTML <em>non</em> sembra difficile</p>
```

**Comment by luca998** [comment]
Ok capito
