### ISSUE TITLE
Pagina completa

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/firstpage#4]
ti ho inviato una pagina completa

**Comment by luca998** [comment]
L'anno scorso abbiamo fatto un po' di html ma non usavamo i tag   lang="it", <meta charset="utf-8"> e
<!doctype html>, sono necessari?

**Comment by FabioZTessitore** [comment]
`<!doctype html>` serve a dire al browser che si vuole usare html5.

`lang="it"` non è un tag, ma un attributo. Si può usare per qualunque tag e serve a specificare la lingua. Messo in `<html>` specifica ovviamente la lingua dell'intera pagina

**Comment by luca998** [comment]
Ah ok va bene
